// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASPNET_MVC_Core.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ASPNET_MVC_Core.Models.Data
{
    public partial interface INorthwindContextProcedures
    {
        Task<List<TenMostExpensiveProductsResult>> TenMostExpensiveProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
